---
- name: "Deploy Nginx ingress chart"
  frantchenco.helm_wrapper.install:
    name: "{{ helm_nginx_name }}"
    chart_repo_url: "{{ helm_nginx_chart_repo_url }}"
    chart_version: "{{ helm_nginx_chart_version }}"
    chart_ref: "{{ helm_nginx_chart_ref }}"
    release_namespace: "{{ helm_nginx_release_namespace }}"
    create_namespace: "{{ helm_nginx_create_namespace }}"
    values: "{{ helm_nginx_values | to_json }}"
    values_files: "{{ helm_nginx_values_files }}"
    wait: "{{ helm_nginx_wait }}"
    disable_hook: "{{ helm_nginx_disable_hook }}"
    force: "{{ helm_nginx_force }}"
    atomic: "{{ helm_nginx_atomic }}"
    skip_crds: "{{ helm_nginx_skip_crds }}"
    update_repo_cache: "{{ helm_nginx_update_repo_cache }}"
    binary_path: "{{ helm_nginx_binary_path }}"
    context: "{{ helm_nginx_context }}"
    kubeconfig: "{{ helm_nginx_kubeconfig }}"
    validate_certs: "{{ helm_nginx_validate_certs }}"